<template>
  <div class="login-page">
    <div class="login-decoration decoration-one"></div><div class="login-decoration decoration-two"></div>
    <div class="login-shell">
      <div class="login-intro"><div class="intro-mark">L</div><div class="eyebrow">LIBRARY MANAGEMENT</div><h1>让每一本书<br><em>都有被发现的机会。</em></h1><p>一个更清晰、更高效的智慧图书馆管理平台。</p><div class="intro-line"><span></span> 智能管理 · 精准服务 · 数据驱动</div></div>
      <el-card class="login-card" shadow="never"><div class="login-brand"><div class="brand-mark">L</div><div><strong>Library</strong><small>智慧图书馆</small></div></div><h2>欢迎回来</h2><p class="muted">登录你的账户，继续管理与探索</p><el-form :model="form" @submit.prevent="login"><el-form-item><el-input v-model="form.username" placeholder="请输入账号" size="large" /></el-form-item><el-form-item><el-input v-model="form.password" type="password" show-password placeholder="请输入密码" size="large" /></el-form-item><el-form-item><el-radio-group v-model="form.role" class="role-switch"><el-radio-button label="ADMIN">管理员</el-radio-button><el-radio-button label="READER">读者</el-radio-button></el-radio-group></el-form-item><el-button type="primary" native-type="submit" class="full" size="large">登录系统 <span>→</span></el-button></el-form><div class="login-footer">安全认证 · 数据加密传输</div></el-card>
    </div>
  </div>
</template>
<script setup>import { reactive } from 'vue';import { useRouter } from 'vue-router';import { ElMessage } from 'element-plus';import http from '../api/http';const router=useRouter();const form=reactive({username:'admin',password:'',role:'ADMIN'});async function login(){try{const r=await http.post('/auth/login',form);if(r.code!==200)throw Error(r.message);localStorage.setItem('library_token',r.data.token);localStorage.setItem('library_user',JSON.stringify(r.data.user));router.push('/')}catch(e){ElMessage.error(e.message||'登录失败')}};</script>
<style scoped>
.login-page { position: relative; display: grid; min-height: 100vh; overflow: hidden; place-items: center; background: #101632; }.login-page::before { position: absolute; inset: 0; background: radial-gradient(circle at 12% 20%, rgba(99, 102, 241, .28), transparent 30%), radial-gradient(circle at 82% 80%, rgba(168, 85, 247, .2), transparent 32%); content: ""; }.login-decoration { position: absolute; border: 1px solid rgba(165, 180, 252, .14); border-radius: 50%; }.decoration-one { width: 580px; height: 580px; left: -270px; top: -220px; }.decoration-two { width: 720px; height: 720px; right: -340px; bottom: -340px; }.login-shell { position: relative; z-index: 1; display: grid; grid-template-columns: minmax(300px, 1fr) 400px; gap: 70px; align-items: center; width: min(930px, calc(100% - 40px)); }.login-intro { color: #fff; }.intro-mark { display: grid; width: 52px; height: 52px; margin-bottom: 35px; place-items: center; color: #fff; border-radius: 17px; background: linear-gradient(135deg, #818cf8, #4f46e5); box-shadow: 0 14px 28px rgba(99, 102, 241, .3); font-size: 27px; font-weight: 800; }.login-intro .eyebrow { color: #a5b4fc; }.login-intro h1 { margin: 16px 0 18px; color: #fff; font-size: clamp(34px, 5vw, 54px); line-height: 1.12; letter-spacing: -.05em; }.login-intro h1 em { color: #a5b4fc; font-style: normal; }.login-intro p { max-width: 360px; color: #aeb9d1; line-height: 1.8; }.intro-line { margin-top: 40px; color: #7e8baa; font-size: 12px; }.intro-line span { display: inline-block; width: 22px; height: 1px; margin-right: 8px; vertical-align: middle; background: #818cf8; }.login-card { width: 400px; padding: 28px; border: 0; border-radius: 24px; background: rgba(255, 255, 255, .96); box-shadow: 0 30px 70px rgba(0, 0, 0, .22); }.login-brand { display: flex; align-items: center; gap: 10px; margin-bottom: 35px; }.login-brand strong { display: block; color: #27334d; font-size: 18px; }.login-brand small { display: block; margin-top: 2px; color: #94a3b8; font-size: 11px; }.brand-mark { display: grid; width: 37px; height: 37px; place-items: center; color: #fff; border-radius: 12px; background: linear-gradient(135deg, #818cf8, #4f46e5); font-weight: 800; }.login-card h2 { margin-bottom: 8px; font-size: 25px; }.muted { margin-bottom: 25px; color: #96a1b4; font-size: 13px; }.role-switch { width: 100%; }.role-switch :deep(.el-radio-button) { flex: 1; }.role-switch :deep(.el-radio-button__inner) { width: 100%; }.full { width: 100%; margin-top: 5px; }.full span { float: right; font-size: 18px; }.login-footer { margin-top: 23px; color: #a3adbd; text-align: center; font-size: 11px; }@media (max-width: 760px) { .login-shell { display: block; width: min(400px, calc(100% - 32px)); }.login-intro { display: none; }.login-card { width: 100%; } }
</style>
