CREATE DATABASE IF NOT EXISTS library_management DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE library_management;

DROP TABLE IF EXISTS borrow_record;
DROP TABLE IF EXISTS notice;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS reader;
DROP TABLE IF EXISTS admin;

CREATE TABLE admin (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '管理员主键',
  username VARCHAR(50) NOT NULL UNIQUE COMMENT '登录账号',
  password VARCHAR(100) NOT NULL COMMENT 'BCrypt密码',
  real_name VARCHAR(50) NOT NULL COMMENT '真实姓名',
  phone VARCHAR(30) DEFAULT NULL COMMENT '联系电话',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0禁用，1启用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB COMMENT='管理员表';

CREATE TABLE reader (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '读者主键',
  reader_no VARCHAR(40) NOT NULL UNIQUE COMMENT '读者证号',
  username VARCHAR(50) NOT NULL UNIQUE COMMENT '登录账号',
  password VARCHAR(100) NOT NULL COMMENT 'BCrypt密码',
  real_name VARCHAR(50) NOT NULL COMMENT '姓名',
  phone VARCHAR(30) DEFAULT NULL COMMENT '联系电话',
  email VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  max_borrow INT NOT NULL DEFAULT 5 COMMENT '最大借阅数量',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0禁用，1启用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB COMMENT='读者表';

CREATE TABLE category (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '分类主键',
  name VARCHAR(80) NOT NULL UNIQUE COMMENT '分类名称',
  description VARCHAR(255) DEFAULT NULL COMMENT '分类描述',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB COMMENT='图书分类表';

CREATE TABLE book (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '图书主键',
  isbn VARCHAR(30) NOT NULL UNIQUE COMMENT 'ISBN编号',
  title VARCHAR(200) NOT NULL COMMENT '书名',
  author VARCHAR(100) NOT NULL COMMENT '作者',
  publisher VARCHAR(150) DEFAULT NULL COMMENT '出版社',
  publish_date DATE DEFAULT NULL COMMENT '出版日期',
  category_id BIGINT NOT NULL COMMENT '分类主键',
  total_stock INT NOT NULL DEFAULT 0 COMMENT '总库存',
  available_stock INT NOT NULL DEFAULT 0 COMMENT '可借库存',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0下架，1可借，2借完',
  cover_url VARCHAR(500) DEFAULT NULL COMMENT '封面地址',
  description TEXT COMMENT '图书简介',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  CONSTRAINT fk_book_category FOREIGN KEY (category_id) REFERENCES category(id)
) ENGINE=InnoDB COMMENT='图书表';

CREATE TABLE notice (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '公告主键',
  title VARCHAR(200) NOT NULL COMMENT '公告标题',
  content TEXT NOT NULL COMMENT '公告内容',
  admin_id BIGINT NOT NULL COMMENT '发布管理员',
  publish_status TINYINT NOT NULL DEFAULT 1 COMMENT '发布状态：0草稿，1已发布',
  published_at DATETIME DEFAULT NULL COMMENT '发布时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  CONSTRAINT fk_notice_admin FOREIGN KEY (admin_id) REFERENCES admin(id)
) ENGINE=InnoDB COMMENT='公告表';

CREATE TABLE borrow_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '借阅记录主键',
  reader_id BIGINT NOT NULL COMMENT '读者主键',
  book_id BIGINT NOT NULL COMMENT '图书主键',
  borrow_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '借出时间',
  due_time DATETIME DEFAULT NULL COMMENT '应还时间',
  return_time DATETIME DEFAULT NULL COMMENT '归还时间',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1借阅中，2正常归还，3异常归还，4逾期',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  operator_id BIGINT DEFAULT NULL COMMENT '操作管理员',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  CONSTRAINT fk_borrow_reader FOREIGN KEY (reader_id) REFERENCES reader(id),
  CONSTRAINT fk_borrow_book FOREIGN KEY (book_id) REFERENCES book(id),
  CONSTRAINT fk_borrow_admin FOREIGN KEY (operator_id) REFERENCES admin(id),
  INDEX idx_borrow_reader_status (reader_id, status), INDEX idx_borrow_book_status (book_id, status)
) ENGINE=InnoDB COMMENT='借阅记录表';

INSERT INTO admin(username,password,real_name) VALUES ('admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '系统管理员');
INSERT INTO category(name,description) VALUES ('文学','文学小说与散文'),('计算机','计算机技术类图书'),('历史','历史与传记');
